#!/usr/bin/env bash
# build_traceability_matrix.sh — build a full traceability matrix from REQ-IDs.
#
# Scans docs/, test files, design docs, evidence, and git history to produce:
#   - docs/_generated/traceability.md   (human-readable)
#   - docs/_generated/traceability.json (machine-readable)
#
# Usage:
#   build_traceability_matrix.sh [--root <docs-dir>] [--output <output-dir>]
#
# Exit codes:
#   0  matrix built (may include warnings for gaps)
#   1  uncovered REQ-IDs found (matrix still generated)
#   2  bad usage / IO failure

set -euo pipefail

# ─── Defaults ───
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
DOCS_DIR="${REPO_ROOT}/docs"
OUTPUT_DIR="${REPO_ROOT}/docs/_generated"
EVIDENCE_DIR="${REPO_ROOT}/.spec-coexist/evidence"

# ─── Parse arguments ───
while [[ $# -gt 0 ]]; do
    case "$1" in
        --root)   DOCS_DIR="$2"; shift 2 ;;
        --output) OUTPUT_DIR="$2"; shift 2 ;;
        -h|--help)
            echo "usage: $0 [--root <docs-dir>] [--output <output-dir>]"
            exit 0
            ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

mkdir -p "${OUTPUT_DIR}"

WARNINGS=0
HAS_UNCOVERED=0

warn() {
    echo "WARN: $*" >&2
    WARNINGS=$((WARNINGS + 1))
}

info() {
    echo "INFO: $*"
}

# ─── Step 1: Collect all REQ-IDs from docs ───
REQ_IDS_FILE="$(mktemp)"
if [[ -d "${DOCS_DIR}" ]]; then
    grep -rhoP 'REQ-[A-Z0-9_]+-[0-9]+' "${DOCS_DIR}" 2>/dev/null \
        | sort -u > "${REQ_IDS_FILE}" || true
fi

REQ_COUNT=$(wc -l < "${REQ_IDS_FILE}" | tr -d ' ')
info "Found ${REQ_COUNT} unique REQ-ID(s) in ${DOCS_DIR}/"

if [[ ${REQ_COUNT} -eq 0 ]]; then
    info "No REQ-IDs found — generating empty matrix"
    cat > "${OUTPUT_DIR}/traceability.md" <<'EMPTYMD'
# Traceability Matrix

_No REQ-IDs found in docs/. Nothing to trace._

Generated by `build_traceability_matrix.sh`.
EMPTYMD
    echo '{"generated_at":"'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'","requirements":[],"orphan_tests":[],"summary":{"total_reqs":0,"covered":0,"uncovered":0,"orphan_tests":0}}' \
        > "${OUTPUT_DIR}/traceability.json"
    info "Empty matrix written to ${OUTPUT_DIR}/"
    rm -f "${REQ_IDS_FILE}"
    exit 0
fi

# ─── Step 2: Collect DES-IDs and their REQ references from design docs ───
DES_MAP_FILE="$(mktemp)"
if [[ -d "${DOCS_DIR}" ]]; then
    # Find design docs and extract DES-ID -> REQ-ID mappings
    find "${DOCS_DIR}" -name '*design*' -name '*.md' -not -name '*template*' -type f 2>/dev/null | while IFS= read -r design_file; do
        # Extract DES-IDs and nearby REQ-IDs from the same section
        current_des=""
        while IFS= read -r line; do
            des_match=$(echo "${line}" | grep -oP 'DES-[A-Z0-9_]+-[0-9]+' || true)
            if [[ -n "${des_match}" ]]; then
                current_des="${des_match}"
            fi
            if [[ -n "${current_des}" ]]; then
                req_matches=$(echo "${line}" | grep -oP 'REQ-[A-Z0-9_]+-[0-9]+' || true)
                for req in ${req_matches}; do
                    echo "${req}|${current_des}|${design_file}"
                done
            fi
        done < "${design_file}"
    done | sort -u > "${DES_MAP_FILE}" 2>/dev/null || true
fi

# ─── Step 3: Collect test file references ───
TEST_MAP_FILE="$(mktemp)"
for pattern in '*test*' '*spec*' '*__tests__*'; do
    find "${REPO_ROOT}" -path '*/.git' -prune -o \
        -path '*/node_modules' -prune -o \
        -path '*/.spec-coexist' -prune -o \
        -path '*/docs' -prune -o \
        -path '*/_generated' -prune -o \
        \( -name "${pattern}" -type f \) -print 2>/dev/null | while IFS= read -r test_file; do
        grep -oP 'REQ-[A-Z0-9_]+-[0-9]+' "${test_file}" 2>/dev/null | while IFS= read -r req_id; do
            # Make path relative to repo root
            rel_path="${test_file#"${REPO_ROOT}"/}"
            echo "${req_id}|${rel_path}"
        done
    done
done | sort -u > "${TEST_MAP_FILE}" 2>/dev/null || true

# ─── Step 4: Collect evidence references ───
EVIDENCE_MAP_FILE="$(mktemp)"
if [[ -d "${EVIDENCE_DIR}" ]]; then
    find "${EVIDENCE_DIR}" -name '*.json' -type f 2>/dev/null | while IFS= read -r ev_file; do
        # Extract proof_type and referenced REQ-IDs
        proof_type=$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(d.get('proof_type','unknown'))" "${ev_file}" 2>/dev/null || echo "unknown")
        result=$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(d.get('result','unknown'))" "${ev_file}" 2>/dev/null || echo "unknown")
        timestamp=$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(d.get('timestamp_utc',''))" "${ev_file}" 2>/dev/null || echo "")
        grep -oP 'REQ-[A-Z0-9_]+-[0-9]+' "${ev_file}" 2>/dev/null | while IFS= read -r req_id; do
            rel_path="${ev_file#"${REPO_ROOT}"/}"
            echo "${req_id}|${proof_type}|${result}|${timestamp}|${rel_path}"
        done
    done | sort > "${EVIDENCE_MAP_FILE}" 2>/dev/null || true
fi

# ─── Step 5: Collect commit SHAs referencing REQ-IDs ───
COMMIT_MAP_FILE="$(mktemp)"
git log --all --oneline --grep='REQ-' 2>/dev/null | while IFS= read -r log_line; do
    sha="${log_line%% *}"
    msg="${log_line#* }"
    echo "${msg}" | grep -oP 'REQ-[A-Z0-9_]+-[0-9]+' 2>/dev/null | while IFS= read -r req_id; do
        echo "${req_id}|${sha}|${msg}"
    done
done | sort > "${COMMIT_MAP_FILE}" 2>/dev/null || true

# ─── Step 6: Find orphan tests (reference non-existent REQ-IDs) ───
ORPHANS_FILE="$(mktemp)"
if [[ -s "${TEST_MAP_FILE}" ]]; then
    cut -d'|' -f1 "${TEST_MAP_FILE}" | sort -u > "$(mktemp -u).test_reqs"
    TEST_REQS="$(cut -d'|' -f1 "${TEST_MAP_FILE}" | sort -u)"
    while IFS= read -r test_req; do
        if ! grep -qx "${test_req}" "${REQ_IDS_FILE}"; then
            grep "^${test_req}|" "${TEST_MAP_FILE}" >> "${ORPHANS_FILE}" || true
        fi
    done <<< "${TEST_REQS}"
fi

# ─── Step 7: Build Markdown output ───
TRACE_MD="${OUTPUT_DIR}/traceability.md"
GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

{
    echo "# Traceability Matrix"
    echo ""
    echo "_Generated at ${GENERATED_AT} by \`build_traceability_matrix.sh\`._"
    echo ""
    echo "## Summary"
    echo ""

    COVERED=0
    UNCOVERED=0

    while IFS= read -r req_id; do
        if grep -q "^${req_id}|" "${TEST_MAP_FILE}" 2>/dev/null; then
            COVERED=$((COVERED + 1))
        else
            UNCOVERED=$((UNCOVERED + 1))
        fi
    done < "${REQ_IDS_FILE}"

    ORPHAN_COUNT=0
    if [[ -s "${ORPHANS_FILE}" ]]; then
        ORPHAN_COUNT=$(cut -d'|' -f1 "${ORPHANS_FILE}" | sort -u | wc -l | tr -d ' ')
    fi

    echo "| Metric | Count |"
    echo "| --- | ---: |"
    echo "| Total REQ-IDs | ${REQ_COUNT} |"
    echo "| Covered (has test) | ${COVERED} |"
    echo "| Uncovered (no test) | ${UNCOVERED} |"
    echo "| Orphan test refs | ${ORPHAN_COUNT} |"
    echo ""

    if [[ ${UNCOVERED} -gt 0 ]]; then
        HAS_UNCOVERED=1
    fi

    # ─── Per-REQ detail table ───
    echo "## Requirements Traceability"
    echo ""
    echo "| REQ-ID | Design Refs | Test Files | Evidence | Commits |"
    echo "| --- | --- | --- | --- | --- |"

    while IFS= read -r req_id; do
        # Design refs
        des_refs=""
        if [[ -s "${DES_MAP_FILE}" ]]; then
            des_refs=$(grep "^${req_id}|" "${DES_MAP_FILE}" 2>/dev/null | cut -d'|' -f2 | sort -u | tr '\n' ', ' | sed 's/, $//' || true)
        fi
        [[ -z "${des_refs}" ]] && des_refs="—"

        # Test files
        test_refs=""
        if [[ -s "${TEST_MAP_FILE}" ]]; then
            test_refs=$(grep "^${req_id}|" "${TEST_MAP_FILE}" 2>/dev/null | cut -d'|' -f2 | sort -u | head -5 | tr '\n' ', ' | sed 's/, $//' || true)
            test_count=$(grep -c "^${req_id}|" "${TEST_MAP_FILE}" 2>/dev/null || echo 0)
            if [[ ${test_count} -gt 5 ]]; then
                test_refs="${test_refs}, ... (+$((test_count - 5)))"
            fi
        fi
        [[ -z "${test_refs}" ]] && test_refs="**UNCOVERED**"

        # Evidence
        ev_refs=""
        if [[ -s "${EVIDENCE_MAP_FILE}" ]]; then
            ev_refs=$(grep "^${req_id}|" "${EVIDENCE_MAP_FILE}" 2>/dev/null | awk -F'|' '{printf "%s(%s)", $2, $3}' | head -c 200 || true)
        fi
        [[ -z "${ev_refs}" ]] && ev_refs="—"

        # Commits
        commit_refs=""
        if [[ -s "${COMMIT_MAP_FILE}" ]]; then
            commit_refs=$(grep "^${req_id}|" "${COMMIT_MAP_FILE}" 2>/dev/null | cut -d'|' -f2 | head -3 | tr '\n' ', ' | sed 's/, $//' || true)
        fi
        [[ -z "${commit_refs}" ]] && commit_refs="—"

        echo "| ${req_id} | ${des_refs} | ${test_refs} | ${ev_refs} | ${commit_refs} |"
    done < "${REQ_IDS_FILE}"

    # ─── Orphan tests ───
    if [[ -s "${ORPHANS_FILE}" ]]; then
        echo ""
        echo "## Orphan Test References"
        echo ""
        echo "Tests referencing REQ-IDs that do not exist in docs/:"
        echo ""
        echo "| REQ-ID (missing) | Test File |"
        echo "| --- | --- |"
        while IFS='|' read -r req_id test_file; do
            echo "| ${req_id} | ${test_file} |"
        done < "${ORPHANS_FILE}"
    fi

} > "${TRACE_MD}"

info "Markdown matrix written to ${TRACE_MD}"

# ─── Step 8: Build JSON output ───
TRACE_JSON="${OUTPUT_DIR}/traceability.json"

python3 -c "
import json, sys

req_ids_file = sys.argv[1]
test_map_file = sys.argv[2]
des_map_file = sys.argv[3]
evidence_map_file = sys.argv[4]
commit_map_file = sys.argv[5]
orphans_file = sys.argv[6]
generated_at = sys.argv[7]

def read_lines(path):
    try:
        with open(path) as f:
            return [l.strip() for l in f if l.strip()]
    except:
        return []

req_ids = read_lines(req_ids_file)

# Parse maps
test_map = {}
for line in read_lines(test_map_file):
    parts = line.split('|', 1)
    if len(parts) == 2:
        test_map.setdefault(parts[0], []).append(parts[1])

des_map = {}
for line in read_lines(des_map_file):
    parts = line.split('|', 2)
    if len(parts) >= 2:
        des_map.setdefault(parts[0], []).append({'des_id': parts[1], 'file': parts[2] if len(parts) > 2 else ''})

evidence_map = {}
for line in read_lines(evidence_map_file):
    parts = line.split('|', 4)
    if len(parts) >= 5:
        evidence_map.setdefault(parts[0], []).append({
            'proof_type': parts[1], 'result': parts[2],
            'timestamp': parts[3], 'file': parts[4]
        })

commit_map = {}
for line in read_lines(commit_map_file):
    parts = line.split('|', 2)
    if len(parts) >= 2:
        commit_map.setdefault(parts[0], []).append({
            'sha': parts[1], 'message': parts[2] if len(parts) > 2 else ''
        })

orphans = []
for line in read_lines(orphans_file):
    parts = line.split('|', 1)
    if len(parts) == 2:
        orphans.append({'req_id': parts[0], 'test_file': parts[1]})

requirements = []
covered = 0
uncovered = 0
for req_id in req_ids:
    tests = test_map.get(req_id, [])
    has_test = len(tests) > 0
    if has_test:
        covered += 1
    else:
        uncovered += 1
    requirements.append({
        'req_id': req_id,
        'design_refs': des_map.get(req_id, []),
        'test_files': tests,
        'evidence': evidence_map.get(req_id, []),
        'commits': commit_map.get(req_id, []),
        'covered': has_test
    })

output = {
    'generated_at': generated_at,
    'requirements': requirements,
    'orphan_tests': orphans,
    'summary': {
        'total_reqs': len(req_ids),
        'covered': covered,
        'uncovered': uncovered,
        'orphan_tests': len(set(o['req_id'] for o in orphans))
    }
}

print(json.dumps(output, indent=2, ensure_ascii=False))
" "${REQ_IDS_FILE}" "${TEST_MAP_FILE}" "${DES_MAP_FILE}" "${EVIDENCE_MAP_FILE}" \
  "${COMMIT_MAP_FILE}" "${ORPHANS_FILE}" "${GENERATED_AT}" > "${TRACE_JSON}"

info "JSON matrix written to ${TRACE_JSON}"

# ─── Cleanup ───
rm -f "${REQ_IDS_FILE}" "${TEST_MAP_FILE}" "${DES_MAP_FILE}" \
      "${EVIDENCE_MAP_FILE}" "${COMMIT_MAP_FILE}" "${ORPHANS_FILE}"

# ─── Report ───
info "Traceability matrix: ${REQ_COUNT} REQ(s), ${COVERED} covered, ${UNCOVERED} uncovered, ${ORPHAN_COUNT} orphan(s)"

if [[ ${HAS_UNCOVERED} -gt 0 ]]; then
    warn "${UNCOVERED} REQ-ID(s) have no test coverage"
    exit 1
fi

echo "build_traceability_matrix.sh: PASSED — all REQ-IDs covered"
exit 0
