#!/usr/bin/env bash
# write_evidence.sh — append a verification evidence record under docs/evidence/
#
# Usage:
#   write_evidence.sh <mode> <subject> <proof-command> <result> [review-ref]
#
# Arguments:
#   mode          "code" or "document"
#   subject       short name of what is being claimed done (e.g. "subsystem:03_payment impl")
#   proof-command the exact command that was run to verify (or a document-mode equivalent
#                 like "reviewed docs/subsystems/03_payment/payment-design.md section 4")
#   result        "pass" or "fail"
#   review-ref    optional — path or identifier of the review outcome that backs this claim
#
# Writes: docs/evidence/verification-<UTC-timestamp>-<slug>.md
# Prints: the path of the evidence file (relative to repo root)
#
# This script is invoked by verification-before-completion at the end of a
# successful gate run, so downstream skills (e.g. a future finishing-subsystem-work)
# can check the evidence directory as a precondition.

set -euo pipefail

if [[ $# -lt 4 ]]; then
    echo "usage: $0 <mode> <subject> <proof-command> <result> [review-ref]" >&2
    exit 2
fi

MODE="$1"
SUBJECT="$2"
PROOF="$3"
RESULT="$4"
REVIEW_REF="${5:-}"

case "${MODE}" in
    code|document) ;;
    *) echo "FAIL: mode must be 'code' or 'document', got '${MODE}'" >&2; exit 2 ;;
esac

case "${RESULT}" in
    pass|fail) ;;
    *) echo "FAIL: result must be 'pass' or 'fail', got '${RESULT}'" >&2; exit 2 ;;
esac

# Locate repo root (fall back to cwd if not in a git repo).
if REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
    :
else
    REPO_ROOT="$(pwd)"
fi

EVIDENCE_DIR="${REPO_ROOT}/docs/evidence"
mkdir -p "${EVIDENCE_DIR}"

TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
SLUG="$(printf '%s' "${SUBJECT}" | tr '[:upper:] /:' '[:lower:]---' | tr -cd 'a-z0-9-' | cut -c1-40)"
if [[ -z "${SLUG}" ]]; then
    SLUG="unnamed"
fi
OUT="${EVIDENCE_DIR}/verification-${TIMESTAMP}-${SLUG}.md"

# Compute a stable hash of the proof invocation + subject so two records for
# the "same" claim can be correlated across reruns.
if command -v sha256sum >/dev/null 2>&1; then
    HASH="$(printf '%s\n%s\n' "${SUBJECT}" "${PROOF}" | sha256sum | cut -c1-12)"
else
    HASH="nohash"
fi

{
    echo "---"
    echo "timestamp_utc: ${TIMESTAMP}"
    echo "mode: ${MODE}"
    echo "subject: ${SUBJECT}"
    echo "result: ${RESULT}"
    echo "proof_hash: ${HASH}"
    [[ -n "${REVIEW_REF}" ]] && echo "review_ref: ${REVIEW_REF}"
    echo "---"
    echo
    echo "# Verification Evidence — ${SUBJECT}"
    echo
    echo "- **Mode:** ${MODE}"
    echo "- **Result:** ${RESULT}"
    echo "- **Proof command / observation:**"
    echo
    echo '```'
    echo "${PROOF}"
    echo '```'
    echo
    if [[ -n "${REVIEW_REF}" ]]; then
        echo "- **Review outcome reference:** ${REVIEW_REF}"
        echo
    fi
    echo "_This file was generated by \`_shared/scripts/write_evidence.sh\` as part of the \`verification-before-completion\` gate. Schema: \`verification-before-completion/references/evidence-schema.md\`._"
} > "${OUT}"

# Print the relative path so the caller can quote it in the completion report.
printf '%s\n' "${OUT#${REPO_ROOT}/}"

# Also write JSON evidence (WP2 dual-write)
JSON_SCRIPT="${REPO_ROOT}/.claude/skills/_shared/scripts/write_evidence_json.sh"
if [[ -x "${JSON_SCRIPT}" ]]; then
    # Map subject to proof_type
    PROOF_TYPE="verification-result"
    case "${SUBJECT}" in
        tdd-red:*)  PROOF_TYPE="tdd-red" ;;
        tdd-green:*) PROOF_TYPE="tdd-green" ;;
        self-review:*|self-check:*) PROOF_TYPE="self-check-result" ;;
        debug-hypothesis:*) PROOF_TYPE="debug-hypothesis" ;;
        tdd-waiver:*) PROOF_TYPE="tdd-waiver" ;;
    esac
    bash "${JSON_SCRIPT}" "${PROOF_TYPE}" "${MODE}" "${SUBJECT}" "${RESULT}" "${PROOF}" -1 "" 2>/dev/null || true
fi
